# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NvdcveAffectedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=30)),
                ('product', models.TextField()),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'nvdcve_affected_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NvdcveDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('published', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('num_of_affected_products', models.IntegerField()),
                ('access_vector', models.CharField(max_length=20)),
                ('access_complexity', models.CharField(max_length=20)),
                ('authentication', models.CharField(max_length=20)),
                ('confidentiality_impact', models.CharField(max_length=20)),
                ('integrity_impact', models.CharField(max_length=20)),
                ('source', models.TextField()),
                ('generated_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'nvdcve_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NvdcveModifiedAffectedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=30)),
                ('product', models.TextField()),
            ],
            options={
                'db_table': 'nvdcve_modified_affected_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NvdcveModifiedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('published', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('num_of_affected_products', models.IntegerField()),
                ('access_vector', models.CharField(max_length=20)),
                ('access_complexity', models.CharField(max_length=20)),
                ('authentication', models.CharField(max_length=20)),
                ('confidentiality_impact', models.CharField(max_length=20)),
                ('integrity_impact', models.CharField(max_length=20)),
                ('source', models.TextField()),
                ('generated_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'nvdcve_modified_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NvdcveModifiedReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=30)),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'nvdcve_modified_references',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NvdcveReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=30)),
                ('url', models.TextField()),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'nvdcve_references',
                'managed': False,
            },
        ),
    ]
