# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NvdcveRecentAffectedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.TextField()),
                ('product', models.TextField()),
            ],
            options={
                'db_table': 'nvdcve_recent_affected_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NvdcveRecentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.TextField()),
                ('summary', models.TextField()),
                ('published', models.TextField()),
                ('last_modified', models.TextField()),
                ('score', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('num_of_affected_products', models.IntegerField()),
                ('access_vector', models.TextField()),
                ('access_complexity', models.TextField()),
                ('authentication', models.TextField()),
                ('confidentiality_impact', models.TextField()),
                ('integrity_impact', models.TextField()),
                ('source', models.TextField()),
                ('generated_on', models.TextField()),
            ],
            options={
                'db_table': 'nvdcve_recent_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NvdcveRecentReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'nvdcve_recent_references',
                'managed': False,
            },
        ),
    ]
